package com.eatif.app.domain.usecase

import com.eatif.app.domain.model.GameDifficulty
import com.eatif.app.domain.model.GameLevel

object GameLevelRegistry {
    private val levels: List<GameLevel> = listOf(
        GameLevel("snake", 1, GameDifficulty.EASY, 0, mapOf("speed" to "slow", "obstacles" to "0")),
        GameLevel("snake", 2, GameDifficulty.EASY, 1, mapOf("speed" to "slow", "obstacles" to "1")),
        GameLevel("snake", 3, GameDifficulty.EASY, 2, mapOf("speed" to "medium", "obstacles" to "2")),
        GameLevel("snake", 4, GameDifficulty.NORMAL, 3, mapOf("speed" to "medium", "obstacles" to "3")),
        GameLevel("snake", 5, GameDifficulty.NORMAL, 4, mapOf("speed" to "medium", "obstacles" to "4")),
        GameLevel("snake", 6, GameDifficulty.NORMAL, 5, mapOf("speed" to "fast", "obstacles" to "3")),
        GameLevel("snake", 7, GameDifficulty.HARD, 6, mapOf("speed" to "fast", "obstacles" to "5")),
        GameLevel("snake", 8, GameDifficulty.HARD, 7, mapOf("speed" to "fast", "obstacles" to "6")),
        GameLevel("snake", 9, GameDifficulty.HARD, 8, mapOf("speed" to "very_fast", "obstacles" to "5")),
        GameLevel("snake", 10, GameDifficulty.HARD, 9, mapOf("speed" to "very_fast", "obstacles" to "7")),
        GameLevel("game2048", 1, GameDifficulty.EASY, 0, mapOf("target" to "256")),
        GameLevel("game2048", 2, GameDifficulty.EASY, 1, mapOf("target" to "512")),
        GameLevel("game2048", 3, GameDifficulty.NORMAL, 2, mapOf("target" to "1024")),
        GameLevel("game2048", 4, GameDifficulty.NORMAL, 3, mapOf("target" to "2048")),
        GameLevel("game2048", 5, GameDifficulty.NORMAL, 4, mapOf("target" to "2048")),
        GameLevel("game2048", 6, GameDifficulty.HARD, 5, mapOf("target" to "4096")),
        GameLevel("game2048", 7, GameDifficulty.HARD, 6, mapOf("target" to "4096")),
        GameLevel("game2048", 8, GameDifficulty.HARD, 7, mapOf("target" to "8192")),
        GameLevel("game2048", 9, GameDifficulty.HARD, 8, mapOf("target" to "8192")),
        GameLevel("game2048", 10, GameDifficulty.HARD, 9, mapOf("target" to "16384")),
        GameLevel("flappy", 1, GameDifficulty.EASY, 0, mapOf("gap" to "wide", "speed" to "slow")),
        GameLevel("flappy", 2, GameDifficulty.EASY, 1, mapOf("gap" to "wide", "speed" to "slow")),
        GameLevel("flappy", 3, GameDifficulty.EASY, 2, mapOf("gap" to "medium", "speed" to "medium")),
        GameLevel("flappy", 4, GameDifficulty.NORMAL, 3, mapOf("gap" to "medium", "speed" to "medium")),
        GameLevel("flappy", 5, GameDifficulty.NORMAL, 4, mapOf("gap" to "medium", "speed" to "fast")),
        GameLevel("flappy", 6, GameDifficulty.NORMAL, 5, mapOf("gap" to "narrow", "speed" to "fast")),
        GameLevel("flappy", 7, GameDifficulty.HARD, 6, mapOf("gap" to "narrow", "speed" to "very_fast")),
        GameLevel("flappy", 8, GameDifficulty.HARD, 7, mapOf("gap" to "narrow", "speed" to "very_fast")),
        GameLevel("flappy", 9, GameDifficulty.HARD, 8, mapOf("gap" to "very_narrow", "speed" to "very_fast")),
        GameLevel("flappy", 10, GameDifficulty.HARD, 9, mapOf("gap" to "very_narrow", "speed" to "insane")),
        GameLevel("spinwheel", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("spinwheel", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("spinwheel", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("spinwheel", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("spinwheel", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("slot", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("slot", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("slot", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("slot", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("slot", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("shooting", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("shooting", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("shooting", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("shooting", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("shooting", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("minesweeper", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("minesweeper", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("minesweeper", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("minesweeper", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("minesweeper", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("tetris", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("tetris", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("tetris", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("tetris", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("tetris", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("rps", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("rps", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("rps", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("rps", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("rps", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("jump", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("jump", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("jump", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("jump", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("jump", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("runner", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("runner", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("runner", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("runner", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("runner", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("climb100", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("climb100", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("climb100", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("climb100", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("climb100", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("needle", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("needle", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("needle", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("needle", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("needle", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("onestroke", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("onestroke", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("onestroke", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("onestroke", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("onestroke", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("boxpusher", 1, GameDifficulty.EASY, 0, mapOf()),
        GameLevel("boxpusher", 2, GameDifficulty.EASY, 1, mapOf()),
        GameLevel("boxpusher", 3, GameDifficulty.NORMAL, 2, mapOf()),
        GameLevel("boxpusher", 4, GameDifficulty.HARD, 3, mapOf()),
        GameLevel("boxpusher", 5, GameDifficulty.HARD, 4, mapOf()),
        GameLevel("match3", 1, GameDifficulty.EASY, 0, mapOf("moves" to "30")),
        GameLevel("match3", 2, GameDifficulty.EASY, 1, mapOf("moves" to "25")),
        GameLevel("match3", 3, GameDifficulty.NORMAL, 2, mapOf("moves" to "20")),
        GameLevel("match3", 4, GameDifficulty.HARD, 3, mapOf("moves" to "15")),
        GameLevel("match3", 5, GameDifficulty.HARD, 4, mapOf("moves" to "10")),
        GameLevel("linklink", 1, GameDifficulty.EASY, 0, mapOf("grid" to "4x4")),
        GameLevel("linklink", 2, GameDifficulty.EASY, 1, mapOf("grid" to "4x5")),
        GameLevel("linklink", 3, GameDifficulty.NORMAL, 2, mapOf("grid" to "5x6")),
        GameLevel("linklink", 4, GameDifficulty.HARD, 3, mapOf("grid" to "6x6")),
        GameLevel("linklink", 5, GameDifficulty.HARD, 4, mapOf("grid" to "6x7")),
        GameLevel("memory", 1, GameDifficulty.EASY, 0, mapOf("grid" to "2x2")),
        GameLevel("memory", 2, GameDifficulty.EASY, 1, mapOf("grid" to "2x3")),
        GameLevel("memory", 3, GameDifficulty.NORMAL, 2, mapOf("grid" to "3x4")),
        GameLevel("memory", 4, GameDifficulty.HARD, 3, mapOf("grid" to "4x4")),
        GameLevel("memory", 5, GameDifficulty.HARD, 4, mapOf("grid" to "4x5")),
        GameLevel("pingpong", 1, GameDifficulty.EASY, 0, mapOf("speed" to "slow")),
        GameLevel("pingpong", 2, GameDifficulty.EASY, 1, mapOf("speed" to "medium")),
        GameLevel("pingpong", 3, GameDifficulty.NORMAL, 2, mapOf("speed" to "fast")),
        GameLevel("pingpong", 4, GameDifficulty.HARD, 3, mapOf("speed" to "very_fast")),
        GameLevel("pingpong", 5, GameDifficulty.HARD, 4, mapOf("speed" to "insane"))
    )

    fun getLevelsForGame(gameId: String): List<GameLevel> = levels.filter { it.gameId == gameId }
    fun getLevel(gameId: String, levelNumber: Int): GameLevel? = levels.find { it.gameId == gameId && it.levelNumber == levelNumber }
    fun getMaxLevelForGame(gameId: String): Int = levels.filter { it.gameId == gameId }.maxOfOrNull { it.levelNumber } ?: 1
}
